# Generated by Django 4.2.5 on 2023-09-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_usuario',
            fields=[
                ('uso_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('usu_email', models.CharField(max_length=100)),
                ('usu_senha', models.CharField(max_length=15)),
            ],
        ),
    ]
