# Generated by Django 4.2.5 on 2023-09-28 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barber_app', '0002_tb_agendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_TelefoneDoAgendamento',
            fields=[
                ('tel_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('tel_age_codigo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='barber_app.tb_agendamento')),
            ],
        ),
    ]
