# Generated by Django 4.2.5 on 2023-09-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barber_app', '0003_tb_telefonedoagendamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tb_servicos',
            fields=[
                ('ser_codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('ser_servico', models.CharField(max_length=45)),
            ],
        ),
    ]
